### ISSUE TITLE
Possibly extend to SVG animations?

### ISSUE THREAD

**Issue by bluthej** [asciinema/agg#49]
Hi,

I just found out about this project, and it’s pretty cool! Awesome work.

I have been looking at tools for recording terminal sessions for a few months now and I’ve been playing around with marionebl’s svg-term-cli to get very small razor sharp animations. However I am encountering some bugs and the project does not look maintained anymore (last commit was in july 2019). So I have been looking at alternatives and agg stood out. However, it sounds like the goal is to only export to gif, not svg animations, so I was wondering if that could be considered as an extension for this project? I would like to give it a go, but I was wondering if there are any inherent limitations that might make it incompatible with the way agg is implemented.

Cheers

**Comment by sickill** [comment]
Hey there :wave: I'm glad you like the project.


agg stands for "**a**sciinema **g**if **g**enerator" and its code architecture is oriented around GIF generation so in order to support SVG it would require significant refactoring. I'd like to keep it small and focused on GIF only though.

However if you're willing to feel free to experiment on it, e.g. fork it, replace image/GIF parts with SVG etc. The more tools around asciinema we have the better :)
