### ISSUE TITLE
Window Change Event

### ISSUE THREAD

**Issue by yarona1993** [asciinema/agg#67]
no support to window change event or initial terminal size

**Comment by ku1ik** [comment]
There's support for overriding the initial terminal size: `--cols` + `--rows` options.

Regarding dynamic resizing throughout the recording: this is tricky because we can't dynamically change the GIF dimensions. With a fixed canvas size we'd need to perform scaling of each frame, which would likely produce text of low quality (either squashed or stretched/blurry), unless we change the rendering approach. In my opinion this is not worth the effort and  therefore supporting dynamic resize is not planned.

**Comment by Adamkadaban** [comment]
For people looking for workarounds to this like I was:

While `agg` and `asciinema play` do not support resizing, `asciinema-server` does.

You can host your own server (and modify upload sizes etc.) and then just screen-record the output. The self-hosted website doesn't support changing speeds, so you can instead manually modify the speed in the file like [this](https://stackoverflow.com/questions/57615791/speed-up-asciinema-by-editing-file)

Make sure to adjust your screen-recording fps to what is desired, especially if you plan to slow slow down your recording in post-processing

It's _very_ hacky, but it works.

**Comment by ku1ik** [comment]
> The self-hosted website doesn't support changing speeds

Indeed, there's no settings for speed, but it's such a simple and valuable thing. Not sure how I missed this. Will implement this soon.

However, you can append `?speed=N` to the recording URL, like this: https://asciinema.org/a/645958?speed=4

More on this here: https://docs.asciinema.org/manual/server/sharing/#speed

**Comment by KJ7LNW** [comment]
> With a fixed canvas size we'd need to perform scaling of each frame, which would likely produce text of low quality (either squashed or stretched/blurry)

+1 for the scaling option.  I think `agg` should scan the file for max row-x-col size, and just shrink if the terminal is smaller than the maximum. No scaling of the image, just unused space in the framebuffer.

Re-open?
